### ISSUE TITLE
Cannot get property 'reactNative' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by beardwin** [gre/react-native-view-shot#286]
### bug report
Building on iOS works perfectly. However, attempts to build and run on an android device or simulator results in a build error. 

```
$> yarn add react-native-view-shot
$> react-native run-android   

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ryanbaldwin/src/github.com/Shopify/arrive-client/node_modules/react-native-view-shot/android/build.gradle' line: 50

* What went wrong:
A problem occurred evaluating project ':react-native-view-shot'.
> Cannot get property 'reactNative' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at checkExecSyncError (child_process.js:603:11)
    at execFileSync (child_process.js:621:15)
    at runOnAllDevices (/Users/ryanbaldwin/src/github.com/Shopify/arrive-client/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/ryanbaldwin/src/github.com/Shopify/arrive-client/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at /Users/ryanbaldwin/src/github.com/Shopify/arrive-client/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/Users/ryanbaldwin/src/github.com/Shopify/arrive-client/node_modules/@react-native-community/cli/build/index.js:164:9)
```

#### Version & Platform
react-native-view-shot@3.1.1
react-native 0.61.2

**Platform:**
Android

#### Expected behavior
I expect it to build. ;)

#### Actual behavior
I does not build. :(

**Comment by beardwin** [comment]
I should note that doing a `yarn add react-native-view-shot@3.0.2` instead of `yarn add react-native-view-shot` does not produce this issue.

**Comment by gre** [comment]
I think that's what https://github.com/gre/react-native-view-shot/commit/4a2317edee1ba0d434ad00e859cb663074bc2121 has fixed? i'll need to deploy a patch

**Comment by jntdst** [comment]
I had same issue and  then according to top answer, change version of react-native-view-shot in package.json to fix it.

**Comment by vinigg2** [comment]
very good @beardwin

**Comment by gre** [comment]
`3.1.2` has been released
