### ISSUE TITLE
Android App crashes only with release APK and release Bunddle

### ISSUE THREAD

**Issue by devedu0714** [gre/react-native-view-shot#399]
Android App crashes only with release APK and release Bunddle

    "react": "17.0.1",
    "react-native": "0.64.1"

crash log
```
    com.facebook.react.uimanager.IllegalViewOperationException: Trying to resolve view with tag 4183 which doesn't exist
        at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveView(NativeViewHierarchyManager.java:103)
        at fr.greweb.reactnativeviewshot.ViewShot.execute(ViewShot.java:171)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:573)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:908)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1079)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:740)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:247)
        at android.app.ActivityThread.main(ActivityThread.java:8656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by ForamPattha** [comment]
@devedu0714 have you found any solution. If found any solution then can you please share here  as I faced also same issue .

**Comment by TomNes94** [comment]
Has this been looked at yet?

**Comment by kanglang** [comment]
I faced also same issue

**Comment by gre** [comment]
A lot has changed since RN 0.64. Please try `npm install react-native-view-shot@alpha` with a recent RN version. Stable v5 coming soon.

**Comment by gre** [comment]
Closing as fixed by v5.0.0.

Your stack trace points at `NativeViewHierarchyManager.resolveView` raising `IllegalViewOperationException` ("Trying to resolve view with tag X which doesn't exist") from the `executor` thread (`ViewShot.execute(ViewShot.java:171)`). This exact path is what v5.0.0 / #630 fixed: `resolveView` now runs on the UIManager queue and is wrapped in `try/catch` so a stale tag rejects the promise (with `E_UNABLE_TO_SNAPSHOT`) instead of crashing the executor.

The reason it surfaces only on release builds is typical Hermes/Proguard timing: minified release runs the JS-side capture trigger faster, so the captured view tag has a higher chance of being unmounted before the native resolve runs.

Please upgrade to `react-native-view-shot@5.0.1` and re-test. The crash should become a `.catch()` rejection. If you still see a hard crash, please open a fresh issue with the new logcat trace.

Release notes: https://github.com/gre/react-native-view-shot/releases/tag/v5.0.0
