### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by gmass0n** [gre/react-native-view-shot#426]
Get this error when tries to capture in android

` const viewShotRef = React.useRef<ViewShot>(null);

  const handleCapture = () => {
    console.log('entrouuuuuuuuuuuuuu entrouuuuuuuuuuuuuu');

    viewShotRef.current.capture().then(uri => console.log({uri}));
  };

  return (
    <View>
      <ViewShot ref={viewShotRef}>
        <Text>sdjghdjklfghdklf</Text>
        <Text>sdjghdjklfghdklf</Text>
        <Text>sdjghdjklfghdklf</Text>
        <Text>sdjghdjklfghdklf</Text>
        <Text>sdjghdjklfghdklf</Text>
        <Text>sdjghdjklfghdklf</Text>
        <Text>sdjghdjklfghdklf</Text>
      </ViewShot>

      <Button title="Capturar" onPress={handleCapture} />
    </View>
  );`

<img width="1115" alt="Screen Shot 2022-07-20 at 17 47 59" src="https://user-images.githubusercontent.com/54415549/180079546-ebd90438-d58b-47f3-aa96-3dd0c3e69840.png">

**Comment by ocsby** [comment]
I am getting same issue on Android 5.1.  Did you find any solution?

**Comment by adelnobel** [comment]
Same problem here, was going to post about it then found your issue.

**Comment by adelnobel** [comment]
Here is the whole stack
```
E/c       ( 7229): Failed to capture view snapshot
E/c       ( 7229): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/c       ( 7229): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7146)
E/c       ( 7229): 	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1033)
E/c       ( 7229): 	at android.view.ViewGroup.invalidateChild(ViewGroup.java:4971)
E/c       ( 7229): 	at android.view.View.invalidateInternal(View.java:12691)
E/c       ( 7229): 	at android.view.View.invalidate(View.java:12655)
E/c       ( 7229): 	at android.view.View.invalidate(View.java:12639)
E/c       ( 7229): 	at android.widget.TextView.checkForRelayout(TextView.java:8094)
E/c       ( 7229): 	at android.widget.TextView.onRtlPropertiesChanged(TextView.java:11004)
E/c       ( 7229): 	at android.view.View.resolvePadding(View.java:14305)
E/c       ( 7229): 	at android.view.View.getPaddingStart(View.java:17620)
E/c       ( 7229): 	at fr.greweb.reactnativeviewshot.a.a()
E/c       ( 7229): 	at fr.greweb.reactnativeviewshot.a.c()
E/c       ( 7229): 	at fr.greweb.reactnativeviewshot.a.b()
E/c       ( 7229): 	at fr.greweb.reactnativeviewshot.c.r()
E/c       ( 7229): 	at fr.greweb.reactnativeviewshot.c.D()
E/c       ( 7229): 	at fr.greweb.reactnativeviewshot.c.c()
E/c       ( 7229): 	at fr.greweb.reactnativeviewshot.c$b.run()
E/c       ( 7229): 	at android.os.Handler.handleCallback(Handler.java:739)
E/c       ( 7229): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/c       ( 7229): 	at android.os.Looper.loop(Looper.java:145)
E/c       ( 7229): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ReactNativeJS( 7229): 'Oops, snapshot failed', [Error: Failed to capture view snapshot]
E/unknown:ReactNative( 7229): console.error: Oops, snapshot failed Error: Failed to capture view snapshot, js engine: hermes, stack:
E/unknown:ReactNative( 7229): _construct@1:143516
E/unknown:ReactNative( 7229): Wrapper@1:143170
E/unknown:ReactNative( 7229): _createSuperInternal@1:141052
E/unknown:ReactNative( 7229): SyntheticError@1:142528
E/unknown:ReactNative( 7229): reactConsoleErrorHandler@1:142161
E/unknown:ReactNative( 7229): anonymous@1:1966810
E/unknown:ReactNative( 7229): tryCallOne@53:15
E/unknown:ReactNative( 7229): anonymous@139:26
E/unknown:ReactNative( 7229): anonymous@1:169478
E/unknown:ReactNative( 7229): _callTimer@1:168422
E/unknown:ReactNative( 7229): _callReactNativeMicrotasksPass@1:168627
E/unknown:ReactNative( 7229): callReactNativeMicrotasks@1:170564
E/unknown:ReactNative( 7229): __callReactNativeMicrotasks@1:149851
E/unknown:ReactNative( 7229): anonymous@1:148983
E/unknown:ReactNative( 7229): __guard@1:149728
E/unknown:ReactNative( 7229): flushedQueue@1:148894
E/unknown:ReactNative( 7229): invokeCallbackAndReturnFlushedQueue@1:148837

**Comment by VMBindraban** [comment]
I am currently getting the same error on android 4 devices. Works fine in android 10+.

**Comment by KodyFintak** [comment]
Also getting the same issue on Nougat, 7.1.1. Is there anything we can do to prevent this issue?

**Comment by hwvenancio** [comment]
I found a solution. On ViewShot.java where you have the following code:
```java
        final Canvas c = new Canvas(bitmap);
        view.draw(c);
```
Force it to run on the UI Thread:
```java
        final Canvas c = new Canvas(bitmap);
        CountDownLatch waitLatch = new CountDownLatch(1);
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                view.draw(c);
                waitLatch.countDown();
            }
        });

        try {
            waitLatch.await();
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
```

**Comment by gre** [comment]
The Android threading model was reworked in v4.0.0 and further improved in `v5@alpha`. Can you try `npm install react-native-view-shot@alpha` and let us know if this is resolved? Stable v5 coming soon.

**Comment by gre** [comment]
v5.0.0 refactored the Android capture path to run setLayerType + view.draw on the UIManager queue, and to resolve the React view on the UIManager queue too, with a hard timeout, cancellation, exception propagation, and CAS-based bitmap pool handoff (see #628 and #630). Please try upgrading; if you still see the assertion warning or the wrong-thread crash, please open a fresh issue with a stack trace pointing at the offending call. Closing as resolved.

Release notes: https://github.com/gre/react-native-view-shot/releases/tag/v5.0.0
