### ISSUE TITLE
Failed to snapshot view tag XXXX

### ISSUE THREAD

**Issue by FernandoAOborges** [gre/react-native-view-shot#545]
```
 @gorhom/bottom-sheet@4.6.4
│ ├─┬ @gorhom/portal@1.0.14
│ │ └── react-native@0.76.1 deduped
│ └── react-native@0.76.1 deduped
├─┬ @miblanchard/react-native-slider@2.6.0
│ └── react-native@0.76.1 deduped
├─┬ @notifee/react-native@9.1.2
│ └── react-native@0.76.1 deduped
├─┬ @react-native-async-storage/async-storage@2.0.0
│ └── react-native@0.76.1 deduped
├─┬ @react-native-community/blur@4.4.1
│ └── react-native@0.76.1 deduped
├─┬ @react-native-community/geolocation@3.4.0
│ └── react-native@0.76.1 deduped
├─┬ @react-native-community/hooks@3.0.0
│ └── react-native@0.76.1 deduped
├─┬ @react-native-firebase/app@20.5.0
│ └── react-native@0.76.1 deduped
├─┬ @react-native-google-signin/google-signin@13.1.0
│ └── react-native@0.76.1 deduped
├─┬ @react-native-menu/menu@1.1.6
│ └── react-native@0.76.1 deduped
├─┬ @react-navigation/bottom-tabs@6.6.1
│ ├─┬ @react-navigation/elements@1.3.31
│ │ └── react-native@0.76.1 deduped
│ └── react-native@0.76.1 deduped
├─┬ @react-navigation/drawer@6.7.2
│ └── react-native@0.76.1 deduped
├─┬ @react-navigation/native-stack@6.11.0
│ └── react-native@0.76.1 deduped
├─┬ @react-navigation/native@6.1.18
│ └── react-native@0.76.1 deduped
├─┬ @react-navigation/stack@6.4.1
│ └── react-native@0.76.1 deduped
├─┬ @testing-library/jest-native@5.4.3
│ └── react-native@0.76.1 deduped
├─┬ @testing-library/react-native@12.7.2
│ └── react-native@0.76.1 deduped
├─┬ react-native-error-boundary@1.2.4
│ └── react-native@0.76.1 deduped
├─┬ react-native-fast-image@8.6.3
│ └── react-native@0.76.1 deduped
├─┬ react-native-gesture-handler@2.20.2
│ └── react-native@0.76.1 deduped
├─┬ react-native-gifted-charts@1.4.41
│ ├─┬ gifted-charts-core@0.1.41
│ │ └── react-native@0.76.1 deduped
│ └── react-native@0.76.1 deduped
├─┬ react-native-google-places-autocomplete@2.5.6
│ └── react-native@0.76.1 deduped
├─┬ react-native-image-crop-picker@0.41.2
│ └── react-native@0.76.1 deduped
├─┬ react-native-image-selfie-segmentation@0.2.3
│ └── react-native@0.76.1 deduped
├─┬ react-native-linear-gradient@2.8.3
│ └── react-native@0.76.1 deduped
├─┬ react-native-maps@1.18.0
│ └── react-native@0.76.1 deduped
├─┬ react-native-pager-view@6.4.1
│ └── react-native@0.76.1 deduped
├─┬ react-native-permissions@4.1.5
│ └── react-native@0.76.1 deduped
├─┬ react-native-reanimated@3.16.1
│ └── react-native@0.76.1 deduped
├─┬ react-native-safe-area-context@4.12.0
│ └── react-native@0.76.1 deduped
├─┬ react-native-screens@3.35.0
│ └── react-native@0.76.1 deduped
├─┬ react-native-svg@15.8.0
│ └── react-native@0.76.1 deduped
├─┬ react-native-tab-view@3.5.2
│ └── react-native@0.76.1 deduped
├─┬ react-native-timeline-flatlist@0.8.0
│ └── react-native@0.76.1 deduped
├─┬ react-native-toast-message@2.2.1
│ └── react-native@0.76.1 deduped
├─┬ react-native-view-shot@3.8.0
│ └── react-native@0.76.1 deduped
├─┬ react-native-vision-camera@4.5.3
│ └── react-native@0.76.1 deduped
├─┬ react-native@0.76.1
│ └─┬ @react-native/virtualized-lists@0.76.1
│   └── react-native@0.76.1 deduped
├─┬ reactotron-react-native@5.1.8
│ ├─┬ react-native-flipper@0.164.0
│ │ └── react-native@0.76.1 deduped
│ └── react-native@0.76.1 deduped
└─┬ toggle-switch-react-native@3.3.0
  └── react-native@0.76.1 deduped
```

```
react-native@0.76.1
react-native-view-shot": "^3.8.0"
```
Platform: Android

Expected Behavior
The captureScreen function in react-native-view-shot should capture an image of the screen and return the URI of the captured image.

Actual Behavior
When calling captureScreen, the following error occurs: Failed to snapshot view tag 2730.

Steps to Reproduce the Behavior
Install the latest version of react-native-view-shot.
Set up and implement screen capture with captureScreen.
```
Run the app on Android with React Native version 0.76.1.
The error Failed to snapshot view tag 2730 appears when trying to capture the screen.
```

**Comment by auliakbarh** [comment]
I got the same error, here's my log cat:

```
Failed to snapshot view tag xxxx
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.uimanager.UIManagerModule.addUIBlock(com.facebook.react.uimanager.UIBlock)' on a null object reference
                                                                                                    	at fr.greweb.reactnativeviewshot.RNViewShotModule.captureRef(RNViewShotModule.java:104)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by smolleyes** [comment]
Hello

Same error here with latest react-native.

What s the best RN version to use for this module ?

Thanks

**Comment by smolleyes** [comment]
@gre have an idear please :) this is the last step to finish my app and i fail on this , so frustrating lol 

thanks

**Comment by FernandoAOborges** [comment]
> @gre have an idear please ? this is the last step to finish my app and i fail on this , so frustrating lol
> 
> thanks

I had to switch packages because it was urgent. I changed to @shopify/react-native-skia, snapshot.

**Comment by smolleyes** [comment]
@FernandoAOborges yeah i tried it yesterday but it returned "Textnodes are not yet supported", strange...

**Comment by duongnguyen17** [comment]
I got the same error

**Comment by du1nabozny** [comment]
Receive this error when switching to Expo 53

**Comment by arisa-s** [comment]
Same issue when I upgraded to Expo53

**Comment by samanmadani71** [comment]
same issue.

**Comment by linushahs** [comment]
Same issue: (NOBRIDGE) LOG  [Error: Failed to snapshot view tag 36]

expo: 52.0.11
react-native: 0.76.3
react-native-view-shot: 4.0.2

**Comment by lisy999** [comment]
Same error

**Comment by lisy999** [comment]
ios is ok  bug android not ok

**Comment by lisy999** [comment]
iOS works well, but Android doesn't work as well.

**Comment by parmaps** [comment]
same issue here
on friday it was working with  expo: "^51.0.38", react-native: "0.74.5" and  react-native-view-shot: "^3.8.0"
yesterday we updated to  expo: "^52.0.0", react-native: "0.76.3", react-native-view-shot: "^3.8.0"
and it stopped working on Android
haven't been able to test on iOS yet

**Comment by senseFy** [comment]
I have created a patch to fix this issue, see:
https://github.com/gre/react-native-view-shot/issues/555

**Comment by CptFabulouso** [comment]
I am on `react-native-view-shot: "^4.0.3"` and `"expo": "~52.0.9",` and it works for me on Android (Samsung, Android 14) . There is no change between 4.0.2 and 4.0.3 on Android. So I wonder if it never works for you guys? Or at what use cases? What phone devices?

**Comment by jkincheloe33** [comment]
> I am on `react-native-view-shot: "^4.0.3"` and `"expo": "~52.0.9",` and it works for me on Android (Samsung, Android 14) . There is no change between 4.0.2 and 4.0.3 on Android. So I wonder if it never works for you guys? Or at what use cases? What phone devices?

Can you share your implementation? I am on react-native-view-shot: "^4.0.3"` and `"expo": "~52.0.31". It works great on iOS but I get this same error on Android.

**Comment by CptFabulouso** [comment]
Pretty basic:
```
function CaptureView() {
  const viewShotRef = useRef<ViewShot | null>(null);
  return (
    <View style={{ flex: 1 }}>
      <ViewShot
        ref={viewShotRef}
        options={props.imageOptions || DEFAULT_IMAGE_OPTIONS}
        style={styles.flex}
      >
        <View
          style={{
            flex: 1,
            backgroundColor: 'green',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <View style={{ width: 100, height: 100, backgroundColor: 'red' }} />
        </View>
      </ViewShot>
      <Button
        title="Capture"
        onPress={() => {
          viewShotRef.current
            ?.capture?.()
            .then((uri) => {
              console.log(uri);
            })
            .catch(console.error);
        }}
      />
    </View>
  );
}
```

I have not run it on production build yet, but I see no mention it's just a production problem. You guys are using new arch, right?

**Comment by jkincheloe33** [comment]
@CptFabulouso Was able to get it working thanks! Seems to be fixed in this release now.

**Comment by petrohusak** [comment]
I've fixed this error, by removing "fileName" property from "options".

**Comment by Accoladecreative** [comment]
I fixed by wrapping my component with this
`<ViewShot ref={viewShotRef} options={{ format: 'jpg', quality: 0.9 }}>` and using
`const imageURI = await viewShotRef.current.capture();`
it worked for me after many days of debugging, i hope this will help someone

**Comment by tkud04** [comment]
y

> I got the same error, here's my log cat:
> 
> ```
> Failed to snapshot view tag xxxx
>                                                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.uimanager.UIManagerModule.addUIBlock(com.facebook.react.uimanager.UIBlock)' on a null object reference
>                                                                                                     	at fr.greweb.reactnativeviewshot.RNViewShotModule.captureRef(RNViewShotModule.java:104)
>                                                                                                     	at com.facebook.jni.NativeRunnable.run(Native Method)
>                                                                                                     	at android.os.Handler.handleCallback(Handler.java:959)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:100)
>                                                                                                     	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
>                                                                                                     	at android.os.Looper.loopOnce(Looper.java:232)
>                                                                                                     	at android.os.Looper.loop(Looper.java:317)
>                                                                                                     	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
>                                                                                                     	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
>                                                                                                     	at java.lang.Thread.run(Thread.java:1012)
> ```

I experienced the same as well! this fixed it for me. I had to manually apply the patch though. https://github.com/gre/react-native-view-shot/issues/555#issue-2792705792

**Comment by gre** [comment]
Fabric support has been overhauled in `v5@alpha`. Can you try `npm install react-native-view-shot@alpha` and let us know if this is resolved? Stable v5 coming soon.

**Comment by beyzanurmakara** [comment]
I’ve solved the issue! :) Previously, I was using react-native-view-shot: 3.8.0 with React Native version 0.68.2. After upgrading to 0.80.2, I started getting the 'Failed to snapshot view tag XXXX' error on Android when using captureRef.

Note: I am currently using "react-native-view-shot": "^4.0.3".

Here is how I fixed it:
I changed my previous implementation from:

<View collapsable={false} ref={ref => this.viewref = ref}>
  ...
</View>

To this:

<ViewShot collapsable={false}>
  <View collapsable={false} ref={ref => { this.viewref = ref }} ...>
    ...
  </View>
</ViewShot>

I wrapped the content with ViewShot, added collapsable={false} to both components, and ensured the ref was assigned correctly without returning it.

I hope this works for you as well!

**Comment by gre** [comment]
Hi @FernandoAOborges and others on this thread,

"Failed to snapshot view tag" is a generic wrapper around any throwable from the capture path. v5.0.0 ships several fixes that likely address it:

- #628 (in v5.0.0): `view.draw()` and view resolution moved onto the UIManager queue with proper exception propagation, hard timeout, and bitmap lifecycle hardening — closes a class of "fails on first/repeated capture" reports.
- #630 (in v5.0.0): `resolveView` moved onto the UIManager queue with try/catch — closes "No view found" + null-currentActivity races.
- #631 (just merged, will ship in v5.0.1): NPE / ClassCastException guard in `applyTransformations` when capturing non-`ViewGroup` roots like `SurfaceView` directly. https://github.com/gre/react-native-view-shot/pull/631

Please re-test on `react-native-view-shot@5.0.0` (or v5.0.1 once it ships) and share whether it's resolved. If not, please open a fresh issue with: RN version, Android API level, the offending view tree, and a logcat stack trace covering the actual exception (the "Failed to snapshot" wrapper now also passes the cause Throwable to `promise.reject` so the JS side has the underlying error).

Closing as likely fixed; happy to re-open if it persists.

Release notes: https://github.com/gre/react-native-view-shot/releases/tag/v5.0.0
